dependencies:
  - name: fluent-bit
    version: ^2.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluent-bit.enabled
  - name: apm-server
    version: ^2.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: apm-server.enabled
  - name: kibana
    version: ^7.4.0
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: elasticsearch
    version: ^7.4.0
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled