# Default values for efk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fluent-bit:
  enabled: true

  backend:
    type: es
    es:
      host: elasticsearch-master
      logstash_prefix: ""
      index: ""
  filter:
    mergeLogKey: logstash_prefix

    extraEntries:
      - Reserve_Data On
      - Regex_Parser kube-tag
  parsers:
    json:
      -
        name: docker
        timeKeep: Off
        Time_Key: time
        timeFormat: "%Y-%m-%dT%H:%M:%S.%L"

apm-server:
  enabled: true
  kind: Deployment
  image:
    repository: docker.elastic.co/apm/apm-server
    tag: 7.4.0
    pullPolicy: IfNotPresent

  # For now we don't use any authorisation/authentication
  rbac:
    create: false
  serviceAccount:
    create: false

  service:
    enabled: true

  config:
    apm-server:
      rum.enabled: true

    output.file.enabled: false
    output:
      elasticsearch:
        hosts: ["elasticsearch-master:9200"]

elasticsearch:
  enabled: true

  antiAffinity: "soft"

  resources:
    limits:
      cpu: "1"
    requests:
      cpu: "25m"
      memory: "512Mi"

  persistence:
    enabled: false

kibana:
  enabled: true

  service:
    port: 443

  ingress:
    enabled: true
    hosts:
      - "xip.io"
